version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - internal

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_MULTIPLE_DATABASES: imageboard, imageboard_identity
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./sh/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - pg-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    links:
      - postgres:postgres
    environment:
      - PGWEB_DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@postgres:${DB_PORT}/postgres?sslmode=disable
    depends_on:
      - postgres
    networks:
      - internal
    ports:
      - "8081:8081"

  imageboard-web:
    build:
      context: .
      dockerfile: apps/imageboard-web/Dockerfile
    container_name: imageboard-web
    env_file:
      - './apps/imageboard-web/.env'
    ports:
      - "80:80"
      - "443:443"
    networks:
      public:
        aliases:
          - auth.spottish.website
          - api.spottish.website
          - spottish.website

  imageboard-api:
    build:
      context: .
      dockerfile: apps/imageboard-api/Dockerfile
    container_name: imageboard-api
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      imageboard-identity-provider:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      SHARED_PATH: /shared
    volumes:
      - shared-data:/shared
    env_file:
      - './apps/imageboard-api/.env'
    networks:
      - internal
      - public

  image-processor:
    build:
      context: .
      dockerfile: apps/image-processor/Dockerfile
    container_name: image-processor
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      SHARED_PATH: /shared
    env_file:
      - './apps/image-processor/.env'
    volumes:
      - shared-data:/shared
    networks:
      - internal

  imageboard-identity-provider:
    build:
      context: .
      dockerfile: apps/imageboard-identity-provider/Dockerfile
    container_name: imageboard-identity-provider
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
    env_file:
      - './apps/imageboard-identity-provider/.env'
    networks:
      - internal
      - public
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificat", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3001/.well-known/openid-configuration"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  imageboard-client:
    build:
      context: .
      dockerfile: apps/imageboard-client/Dockerfile
    container_name: imageboard-client
    env_file:
      - './apps/imageboard-client/.env'
    depends_on:
      imageboard-identity-provider:
        condition: service_healthy
    networks:
      - internal
      - public

volumes:
  pg-data:
  redis-data:
  shared-data:

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
