version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-bridge

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_MULTIPLE_DATABASES: imageboard, imageboard_identity
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - ./sh/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-bridge

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    networks:
      - app-bridge
    environment:
      - PGWEB_DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@postgres:${DB_PORT}/postgres?sslmode=disable
    depends_on:
      - postgres

  image-server:
    build:
      context: .
      dockerfile: apps/image-server/Dockerfile
    container_name: image-server
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT:-5432}
      SHARED_PATH: /shared
    volumes:
      - shared-data:/shared
    ports:
      - '${API_PORT:-3000}:3000'
    networks:
      - app-bridge

  image-processor:
    build:
      context: .
      dockerfile: apps/image-processor/Dockerfile
    container_name: image-processor
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      SHARED_PATH: /shared
    env_file:
      - '.env'
    volumes:
      - shared-data:/shared
    networks:
      - app-bridge

  imageboard-identity-provider:
    build:
      context: .
      dockerfile: apps/imageboard-identity-provider/Dockerfile
    container_name: imageboard-identity-provider
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
    ports:
      - '3001:3001'
    env_file:
      - './apps/imageboard-identity-provider/.env'
    networks:
      - app-bridge

    develop:
      watch:
        - action: sync+restart
          path: ./apps/imageboard-identity-provider
          target: /src/imageboard-identity-provider
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/imageboard-identity-provider/package.json

volumes:
  pg-data:
  redis-data:
  shared-data:

networks:
  app-bridge:
    driver: bridge
