version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  image-server:
    image: ghcr.io/wittmannd/imageboard-image-server:latest
    container_name: image-server
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SHARED_PATH: /shared
    volumes:
      - shared-data:/shared
    ports:
      - "3000:3000"

  image-processor:
    image: ghcr.io/wittmannd/imageboard-image-processor:latest
    container_name: image-processor
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SHARED_PATH: /shared
    volumes:
      - shared-data:/shared

volumes:
  redis-data:
  shared-data:
