$schema: './schema/image-transform-config.schema.json'
transform:
  - operation: resize
    args:
      width: ${{variables.tile.width}}
      height: ${{variables.tile.height}}
      fir: ${{variables.tile.fit}}
  - operation: jpeg
    args:
      quality: 80
  - operation: save
    args:
      key: ${{file.name}}_tile.jpeg
