mediaSource:
  basePath: './'

mediaStorage:
  basePath: './'

transform:
  - operation: 'webp'
    args:
      quality: 82
      effort: 5
      smartSubsample: true

  - - operation: 'webp'
      args:
        quality: 82
        effort: 5
        smartSubsample: true

    - operation: 'webp'
      args:
        quality: 82
        effort: 5
        smartSubsample: true